{
 "title": "New dashboard Copy",
 "time": { "from": "2025-09-06T16:43:34.959Z", "to": "2025-09-06T17:13:34.959Z" },
 "panels": [
  {
   "title": "Количество места на файловой системе",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{fstype=~\"ext4|xfs\"}"
    },
    {
     "expr": "node_filesystem_size_bytes{fstype=~\"ext4|xfs\"}"
    }
   ]
  },
  {
   "title": "Количество свободной оперативной памяти",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{job=\"nodeexporter\"}"
    }
   ]
  },
  {
   "title": "CPULA 1/5/15",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(node_load1{job=\"nodeexporter\"})"
    },
    {
     "expr": "avg(node_load5{job=\"nodeexporter\"})"
    },
    {
     "expr": "avg(node_load15{job=\"nodeexporter\"})"
    }
   ]
  },
  {
   "title": "Утилизация CPU",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - avg(irate(node_cpu_seconds_total{job=\"nodeexporter\", mode=\"idle\"}[1m])) * 100"
    }
   ]
  }
 ]
}